server:
  port: 8080
  servlet:
    context-path: /client

security:
  basic:
    enabled: false

spring:
  security:
    oauth2:
      client:
        registration:
          teemo:
            clientId: foo
            clientSecret: bar
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8080/client/login/oauth2/code/teemo
        provider:
          teemo:
            authorizationUri: http://localhost:8082/auth/oauth/authorize
            tokenUri: http://localhost:8082/auth/oauth/token
            userInfoUri: http://localhost:8081/resource/me
            user-name-attribute: name

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  resources:
    chain:
      cache: false # static content caching disable