server:
  port: 8080

spring:
  profiles: production

  security:
    oauth2:
      client:
        registration:
          teemo:
            # client_url = "http://mainwebapplication.herokuapp.com/client"
            # resource_server_url = "http://oauth2resourceserver.herokuapp.com/resource"
            # authorization_server_url = "http://oauth2authorizationserver.herokuapp.com/auth"
            # provider_name = "teemo"

            # redirectUri : <client_url>/login/oauth2/code/<provider_name>  (default)
            redirectUri: http://mainwebapplication.herokuapp.com/client/login/oauth2/code/teemo

        # Custom Oauth2 Provider
        provider:
          teemo:
            # authorizationUri: <authorization_server_url>/oauth/authorize  (default)
            authorizationUri: http://oauth2authorizationserver.herokuapp.com/auth/oauth/authorize

            # tokenUri: <authorization_server_url>/oauth/token  (default)
            tokenUri: http://oauth2authorizationserver.herokuapp.com/auth/oauth/token

            # userInfoUri: <resource_server_url>/me  (default)
            userInfoUri: http://oauth2resourceserver.herokuapp.com/resource/me

            # custom property
            logoutSuccessUrl: http://oauth2authorizationserver.herokuapp.com/auth/logout